### ISSUE TITLE
[Add] Guide on how to run this project locally on host machine

### ISSUE THREAD

**Issue by sree-hari-s** [sree-hari-s/Ecommerce_New_Project#3]
Some fixes need to be done in the requirements.txt

**Comment by yr1404** [comment]
I have some questions.

> [Add] Guide on how to run this project locally on host machine  

This is to be added in Readme, isn't it?

> Some fixes need to be done in the requirements.txt

Can you specify the changes?

**Comment by sree-hari-s** [comment]
After creating Environment
python -m venv env

Activate the environment 
Source env/bin/activate

Install the required packages 
pip install -r requirements.txt

there is some error showing up, try from your en

**Comment by SimardeepSingh-zsh** [comment]
**Update Package Versions**: If the issue involves outdated package versions or conflicts between packages, consider updating the package versions in the `requirements.txt` file. You can specify the desired version of a package using the format `package-name==version`.

**Remove Unnecessary Packages**: If there are packages listed in the `requirements.txt` file that are no longer needed for the project, remove them to simplify the dependencies.

**Comment by sree-hari-s** [comment]
Thanks for the reply @SimardeepSingh-zsh will update and try to close the issue.
